language: python
cache: pip
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
  - python -m pytest tests/unit --cov=tohsaka --cov-report html --cov-report term
  - python -m pytest tests/mystic
after_success:
  - coveralls